controller_manager_ns: ''
controller_list:
  - name:              hsrb/arm_trajectory_controller
    action_ns:         follow_joint_trajectory
    type:              FollowJointTrajectory
    default:           true
    joints:
      - arm_lift_joint
      - arm_flex_joint
      - arm_roll_joint
      - wrist_flex_joint
      - wrist_roll_joint
      
  - name:              hsrb/gripper_trajectory_controller
    action_ns:         follow_joint_trajectory
    type:              FollowJointTrajectory
    default:           true
    joints:
      - hand_l_spring_proximal_joint
      - hand_motor_joint
      - hand_r_spring_proximal_joint

  - name:              hsrb/head_trajectory_controller
    action_ns:         follow_joint_trajectory
    type:              FollowJointTrajectory
    default:           true
    joints:
      - head_pan_joint
      - head_tilt_joint
