# Position Controllers ---------------------------------------
head_pan_joint_position_controller:
  type:                                position_controllers/JointPositionController
  joint:                               head_pan_joint

head_tilt_joint_position_controller:
  type:                                position_controllers/JointPositionController
  joint:                               head_tilt_joint

arm_lift_joint_position_controller:
  type:                                position_controllers/JointPositionController
  joint:                               arm_lift_joint

arm_flex_joint_position_controller:
  type:                                position_controllers/JointPositionController
  joint:                               arm_flex_joint

arm_roll_joint_position_controller:
  type:                                position_controllers/JointPositionController
  joint:                               arm_roll_joint

wrist_flex_joint_position_controller:
  type:                                position_controllers/JointPositionController
  joint:                               wrist_flex_joint

wrist_roll_joint_position_controller:
  type:                                position_controllers/JointPositionController
  joint:                               wrist_roll_joint

hand_motor_joint_position_controller:
  type:                                effort_controllers/JointPositionController
  joint:                               hand_motor_joint
  pid: {p: 500, i: 5, d: 1}

hand_l_spring_proximal_joint_position_controller:
  type:                                effort_controllers/JointPositionController
  joint:                               hand_l_spring_proximal_joint
  pid: {p: 500, i: 5, d: 1}

hand_r_spring_proximal_joint_position_controller:
  type:                                effort_controllers/JointPositionController
  joint:                               hand_r_spring_proximal_joint
  pid: {p: 500, i: 5, d: 1}
