hsrb:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  arm_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - arm_lift_joint
      - arm_flex_joint
      - arm_roll_joint
      - wrist_flex_joint
      - wrist_roll_joint

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  gripper_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - hand_l_spring_proximal_joint
      - hand_motor_joint
      - hand_r_spring_proximal_joint

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  head_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - head_pan_joint
      - head_tilt_joint
